### ISSUE TITLE
track_process: PROC_EVENT* undeclared on CentOS 6

### ISSUE THREAD

**Issue by chiak597** [acassen/keepalived#1119]
I'm trying to compile keepalived-2.0.12 on CentOS 6.10.

Configure command passed without any errors:
`./configure --with-init=SYSV --disable-nftables`

However, make fails on track_process.c:
```
CC     track_process.o
track_process.c: In function ‘handle_proc_ev’:
track_process.c:657: error: ‘PROC_EVENT_PTRACE’ undeclared (first use in this function)
track_process.c:657: error: (Each undeclared identifier is reported only once
track_process.c:657: error: for each function it appears in.)
track_process.c:666: error: ‘PROC_EVENT_COMM’ undeclared (first use in this function)
track_process.c:673: error: ‘union <anonymous>’ has no member named ‘comm’
track_process.c:673: error: ‘union <anonymous>’ has no member named ‘comm’
track_process.c:675: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function)
make[2]: *** [track_process.o] Error 1 
```

My first thought was that CONFIG_PROC_EVENTS is not set (#1099), but it is there.
```
[root@centos ~] grep PROC_EVENTS /boot/config-2.6.32-754.10.1.el6.x86_64
CONFIG_PROC_EVENTS=y
```

On CentOS 7, package is compiled without any issue, so there might be an issue with kernel version.

**Comment by pqarmitage** [comment]
Commit 1637032 resolves the compilation failure
Commit 975315b allow track_process to work on pre 3.2 kernel but with the limitation that changes to a process name (/proc/PID/comm) aren't detected
Commit 2d48f81 means that you will no longer have to specify --disable-nftables

I'm not sure how to reliably detect the init type. `/sbin/init --version` reports that it is upstart, which is why configure is selecting the wrong type.

**Comment by chiak597** [comment]
Thanks.

Regarding init: CentOS 6 uses upstart, but many people (including me) still prefer to use sysvinit scripts on it. 
It is OK to specify init manually, but when I run `./configure --with-init=SYSV` to generate `.spec` file, init option is missing from resulting file and I need to patch it manually (otherwise upstart is autoselected during rpmbuild). Is that an expected behavior?

**Comment by pqarmitage** [comment]
Commit 9c94b40 should resolve setting the init option in the spec file.

**Comment by feckert** [comment]
@pqarmitage I have update in OpenWrt recently to the newest version 2.0.19. An user reported problems in some arch wich does not have defined in the kernel config `CONFIG_PROC_EVENTS`.
The system compiles but complains on runtime the follwoing error.

> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: Starting Keepalived v2.0.19 (10/24,2019), git commit reboot-10737-g37f853f341
> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: Running on Linux 4.14.149 #0 SMP Thu Oct 24 14:18:26 2019 (built for Linux 4.14)
> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: Command line: '/usr/sbin/keepalived' '-n' '-f' '/tmp/keepalived.conf'
> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: Opening file '/tmp/keepalived.conf'.
> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: track_process not available - is CONFIG_PROC_EVENTS enabled in kernel config?
> Mon Nov  4 11:58:19 2019 daemon.info Keepalived[3254]: pidfile_write : Cannot open /run/keepalived.pid pidfile

I think its not enough to check if the c kernel definitions are valid but we need also check if the kernel params are enbabled. So could we check this?
