### ISSUE TITLE
1.3.5 Build failure on CentOS7 with kernel updated to recent version

### ISSUE THREAD

**Issue by fenice2** [acassen/keepalived#559]
I've just downloaded the latest 1.3.5 and it throws an error when I try to build it on CentOS7, this is a fairly standard install with an updated kernel: 4.10.4-1.el7.elrepo.x86_64

I did also try this build with a normal CentOS7 kernel: 3.10.0-123.el7.x86_64 That had the same result, the error I see is:

In file included from vrrp_iptables_calls.c:47:0:
/usr/include/linux/netfilter/xt_set.h:69:31: error: field 'packets' has incomplete type
  struct ip_set_counter_match0 packets;
                               ^
/usr/include/linux/netfilter/xt_set.h:70:31: error: field 'bytes' has incomplete type
  struct ip_set_counter_match0 bytes;
                               ^
make[2]: *** [vrrp_iptables_calls.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/a.user/rpmbuild/BUILD/keepalived-1.3.5/keepalived/vrrp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/a.user/rpmbuild/BUILD/keepalived-1.3.5/keepalived'
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.nlSLXz (%build)

If there's anything I've missed, just let me know.

**Comment by pqarmitage** [comment]
I've tested this on a vanilla Centos 7, with Linux 3.10.0-514.10.2.el7.x86_64 and it builds without a problem.

The problem you are experiencing is caused by the libipset header files being out of step with the kernel header files which you have updated to 4.10.4. There is an absolute nightmare regarding header file inclusion, with libipset having copies of some of the kernel header files. Unfortunately we need to include some libipset header files and some kernel header files, and as a consequence we have to set a kernel include guard (see lines 42-46 of vrrp_iptables_calls.c) to stop linux/netfilter/ipset/ip_set.h being included, since libipset/linux_ip_set.h duplicates a large part of it. Unfortunately, with libipset/linux_ip_set.h being out of date compared to linux/netfilter/xt_set.h, we end up with the struct ip_set_counter_match0 not being defined.

As a temporary workaround you could add
```
struct ip_set_counter_match0 {
     __u8 op;
     __u64 value;
} ;
```
in vrrp_iptables_calls.c immediately before linux/netfilter/ip_set.h is included (i.e. at line 47),
or alternatively install an up-to-date version of libipset and its header files.

I will look to see what I can do regarding header file inclusion to try and resolve the problem, but I don't think it will be a quick solution.

**Comment by fenice2** [comment]
Thanks for your quick reply. So it's my fault for upgrading the kernel? :)

Just for confirmation that I have the correct piece of code, this is what I see in .......keepalived/vrrp/vrrp_iptables_calls.c - the bold item is at line 47 but it's slightly different in name than the one you mentioned. Is that the correct place for the inserting your workaround prior to that line or is it prior to "linux_ip_set.h"?

#include <xtables.h>
#include <libiptc/libiptc.h>
#include <libiptc/libip6tc.h>
#ifdef _HAVE_LIBIPSET_
#include <libipset/linux_ip_set.h>
#if defined XT_SET_H_ADD_IP_SET_H_GUARD
#define _IP_SET_H
#elif defined XT_SET_H_ADD_UAPI_IP_SET_H_GUARD
#define _UAPI_IP_SET_H
#endif
**#include <linux/netfilter/xt_set.h>**
#endif
#include <unistd.h>
#include <signal.h>
#include <stdint.h>
#ifdef _LIBXTABLES_DYNAMIC_
#include <sys/types.h>
#include <sys/stat.h>
#endif

I'm not worried about a quick fix, when you have the time suits me fine.

**Comment by pqarmitage** [comment]
Yes, immediately before the line:
**#include <linux/netfilter/xt_set.h>**

**Comment by fenice2** [comment]
Thanks for the confirmation. Built, installed and works a treat. :)

This issue is closed as far as I'm concerned.

**Comment by pqarmitage** [comment]
There is still an issue regarding building with conflicting versions of ip_set.h which needs to be resolved.

**Comment by fenice2** [comment]
So there is, my apologies for closing it and my enthusiasm for your fixes sometimes gets the better of me.

**Comment by pqarmitage** [comment]
Commit 510c6b4 resolves this issue. I've changed the way it sorts out which header file to included, and decided to include the kernel header file in preference to the libipset version.
