### ISSUE TITLE
Can't compile on alpine 3.6

### ISSUE THREAD

**Issue by BertrandGouny** [acassen/keepalived#843]
Hello,
i have some errors trying to compile keepalived with alpine 3.6. I guess this comes from gcc import ?
Any idea how to fix this? Thanks

**./configure --disable-dynamic-linking && make && make install**

Errors: 
```
./configure: line 7301: test: !=: unary operator expected
./configure: line 10584: test: =: unary operator expected
error: redefinition of 'struct ethhdr'
```

Pakages installed: 
```
autoconf \
curl \
gcc \
ipset \
ipset-dev \
iptables \
iptables-dev \
libnfnetlink \
libnfnetlink-dev \
libnl3 \
libnl3-dev \
make \
musl-dev \
openssl \
openssl-dev \
```

Logs : 
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /bin/grep
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking for strip... strip
checking for ldd... ldd
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether -fPIE and -pie are supported... yes
checking for -Wimplicit-fallthrough... no
checking how to run the C preprocessor... gcc -E
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking asm/types.h usability... yes
checking asm/types.h presence... yes
checking for asm/types.h... yes
checking linux/ethtool.h usability... yes
checking linux/ethtool.h presence... yes
checking for linux/ethtool.h... yes
checking linux/icmpv6.h usability... yes
checking linux/icmpv6.h presence... yes
checking for linux/icmpv6.h... yes
checking linux/if_ether.h usability... yes
checking linux/if_ether.h presence... yes
checking for linux/if_ether.h... yes
checking linux/if_packet.h usability... yes
checking linux/if_packet.h presence... yes
checking for linux/if_packet.h... yes
checking linux/ip.h usability... yes
checking linux/ip.h presence... yes
checking for linux/ip.h... yes
checking linux/sockios.h usability... yes
checking linux/sockios.h presence... yes
checking for linux/sockios.h... yes
checking linux/types.h usability... yes
checking linux/types.h presence... yes
checking for linux/types.h... yes
checking for linux/fib_rules.h... yes
checking for linux/if_addr.h... yes
checking for linux/if_link.h... yes
checking for linux/if_arp.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for an ANSI C-conforming const... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for dup2... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for select... yes
checking for setenv... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for uname... yes
checking for pipe2... yes
checking whether ETHERTYPE_IPV6 is declared... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking for MD5_Init in -lcrypto... yes
checking for SSL_CTX_new in -lssl... yes
checking SSL_set_tlsext_host_name() - may be a definition... yes
checking for SSL_CTX_set_verify_depth... yes
checking for SSL_set0_rbio... no
checking for OPENSSL_init_crypto... no
checking for nl_socket_alloc in -lnl-3... yes
checking for genl_connect in -lnl-genl-3... yes
./configure: line 7301: test: !=: unary operator expected
checking for linux/rtnetlink.h... yes
checking libnfnetlink/libnfnetlink.h usability... yes
checking libnfnetlink/libnfnetlink.h presence... yes
checking for libnfnetlink/libnfnetlink.h... yes
checking netlink/netlink.h usability... yes
checking netlink/netlink.h presence... yes
checking for netlink/netlink.h... yes
checking netlink/genl/ctrl.h usability... yes
checking netlink/genl/ctrl.h presence... yes
checking for netlink/genl/ctrl.h... yes
checking netlink/genl/genl.h usability... yes
checking netlink/genl/genl.h presence... yes
checking for netlink/genl/genl.h... yes
checking whether RTA_ENCAP is declared... yes
checking whether RTA_EXPIRES is declared... no
checking whether RTA_NEWDST is declared... yes
checking whether RTA_PREF is declared... yes
checking whether FRA_SUPPRESS_PREFIXLEN is declared... yes
checking whether FRA_SUPPRESS_IFGROUP is declared... yes
checking whether FRA_TUN_ID is declared... yes
checking whether RTAX_CC_ALGO is declared... yes
checking whether RTAX_QUICKACK is declared... yes
checking whether RTEXT_FILTER_SKIP_STATS is declared... yes
checking whether FRA_L3MDEV is declared... no
checking whether FRA_UID_RANGE is declared... no
checking whether RTAX_FASTOPEN_NO_COOKIE is declared... no
checking whether RTA_VIA is declared... yes
checking whether FRA_OIFNAME is declared... yes
checking whether IFA_FLAGS is declared... yes
checking whether LWTUNNEL_ENCAP_MPLS is declared... yes
checking whether LWTUNNEL_ENCAP_ILA is declared... yes
checking linux/netfilter/x_tables.h usability... yes
checking linux/netfilter/x_tables.h presence... yes
checking for linux/netfilter/x_tables.h... yes
checking xtables.h usability... yes
checking xtables.h presence... yes
checking for xtables.h... yes
checking libiptc/libip6tc.h usability... yes
checking libiptc/libip6tc.h presence... yes
checking for libiptc/libip6tc.h... yes
checking libiptc/libiptc.h usability... yes
checking libiptc/libiptc.h presence... yes
checking for libiptc/libiptc.h... yes
checking libiptc/libxtc.h usability... yes
checking libiptc/libxtc.h presence... yes
checking for libiptc/libxtc.h... yes
checking for iptc_init in -liptc... yes
checking for ipset_session_init in -lipset... yes
checking libipset/data.h usability... yes
checking libipset/data.h presence... yes
checking for libipset/data.h... yes
checking libipset/linux_ip_set.h usability... yes
checking libipset/linux_ip_set.h presence... yes
checking for libipset/linux_ip_set.h... yes
checking libipset/session.h usability... yes
checking libipset/session.h presence... yes
checking for libipset/session.h... yes
checking libipset/types.h usability... yes
checking libipset/types.h presence... yes
checking for libipset/types.h... yes
checking for xtables_insmod in -lxtables... yes
checking linux/netfilter/xt_set.h usability... yes
checking linux/netfilter/xt_set.h presence... yes
checking for linux/netfilter/xt_set.h... yes
checking for struct xt_set_info_match_v1.match_set.index... yes
checking for struct xt_set_info_match_v3.match_set.index... yes
checking for struct xt_set_info_match_v4.match_set.index... yes
checking whether XT_EXTENSION_MAXNAMELEN is declared... yes
checking for linux/if.h and net/if.h namespace collision... yes
checking for libiptc/libiptc.h linux/if.h and net/if.h namespace collision... no
checking linux/ip_vs.h usability... yes
checking linux/ip_vs.h presence... yes
checking for linux/ip_vs.h... yes
checking whether IP_VS_SVC_F_ONEPACKET is declared... yes
checking whether IPVS_DEST_ATTR_ADDR_FAMILY is declared... yes
checking whether IPVS_DAEMON_ATTR_SYNC_MAXLEN is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_GROUP is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_GROUP6 is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_PORT is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_TTL is declared... yes
checking whether IPVS_SVC_ATTR_STATS64 is declared... yes
checking whether IPVS_DEST_ATTR_STATS64 is declared... yes
checking whether IFLA_MACVLAN_MODE is declared... yes
checking whether MACVLAN_MODE_PRIVATE is declared... yes
checking whether SOCK_NONBLOCK is declared... yes
checking whether SOCK_CLOEXEC is declared... yes
checking whether IPVS_SVC_ATTR_PE_NAME is declared... yes
checking whether O_PATH is declared... yes
checking whether GLOB_BRACE is declared... no
checking whether FRA_SRC is declared... yes
checking whether IFLA_INET6_ADDR_GEN_MODE is declared... yes
checking whether SO_MARK is declared... yes
checking whether CLONE_NEWNET is declared... yes
checking for setns... yes
checking for sphinx-build... No
./configure: line 10584: test: =: unary operator expected

checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating keepalived/Makefile
config.status: creating lib/Makefile
config.status: creating keepalived/core/Makefile
config.status: creating keepalived.spec
config.status: creating genhash/Makefile
config.status: creating keepalived/check/Makefile
config.status: creating keepalived/vrrp/Makefile
config.status: creating doc/Makefile
config.status: creating bin_install/Makefile
config.status: creating keepalived/dbus/Makefile
config.status: creating keepalived/etc/Makefile
config.status: creating keepalived/etc/init/Makefile
config.status: creating keepalived/etc/init.d/Makefile
config.status: creating lib/config.h
config.status: executing depfiles commands

Keepalived configuration
------------------------
Keepalived version       : 1.4.3
Compiler                 : gcc
Preprocessor flags       :  -I/usr/include/libnl3    
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2 -D_GNU_SOURCE -fPIE     
Linker flags             :  -pie
Extra Lib                : -lcrypto -lssl -lnl-genl-3 -lnl-3 -lip4tc -lip6tc -lxtables -lipset
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
smtp-alert debugging     : No
Use Json output          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : 3
Use IPv4 devconf         : No
Use libiptc              : Yes
Use libipset             : Yes
init type                : undetected
Build genhash            : Yes
Build documentation      : No
Making all in lib
make[1]: Entering directory '/container/keepalived-sources/lib'
make  all-am
make[2]: Entering directory '/container/keepalived-sources/lib'
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       scheduler.o
  CC       vector.o
  CC       list.o
  CC       html.o
  CC       parser.o
  CC       signals.o
  CC       logger.o
  CC       rttables.o
  CC       assert.o
  AR       liblib.a
make[2]: Leaving directory '/container/keepalived-sources/lib'
make[1]: Leaving directory '/container/keepalived-sources/lib'
Making all in keepalived
make[1]: Entering directory '/container/keepalived-sources/keepalived'
Making all in core
make[2]: Entering directory '/container/keepalived-sources/keepalived/core'
  CC       main.o
  CC       daemon.o
  CC       pidfile.o
  CC       layer4.o
  CC       smtp.o
  CC       global_data.o
  CC       global_parser.o
  CC       process.o
  CC       keepalived_netlink.o
In file included from /usr/include/net/ethernet.h:10:0,
                 from ./../include/vrrp_vmac.h:32,
                 from keepalived_netlink.c:50:
/usr/include/netinet/if_ether.h:101:8: error: redefinition of 'struct ethhdr'
 struct ethhdr {
        ^~~~~~
In file included from /usr/include/linux/netdevice.h:29:0,
                 from ./../include/vrrp_if.h:36,
                 from ./../include/keepalived_netlink.h:43,
                 from keepalived_netlink.c:48:
/usr/include/linux/if_ether.h:140:8: note: originally defined here
 struct ethhdr {
        ^~~~~~
make[2]: *** [Makefile:368: keepalived_netlink.o] Error 1
make[2]: Leaving directory '/container/keepalived-sources/keepalived/core'
make[1]: Leaving directory '/container/keepalived-sources/keepalived'
make[1]: *** [Makefile:578: all-recursive] Error 1
make: *** [Makefile:425: all-recursive] Error 1
```

**Comment by pqarmitage** [comment]
@BertrandGouny there was an error in commit afc4508 which is resolved by commit 58ae2ba
