### ISSUE TITLE
Build failure with kernel < 3.14

### ISSUE THREAD

**Issue by ffontaine** [acassen/keepalived#2094]
Since version 2.2.5 and https://github.com/acassen/keepalived/commit/a28d56234459647e649d6a46028b976a662bc7a0, the following build failure is raised with kernel < 3.14 (as `NFT_META_L4PROTO` is only available since https://github.com/torvalds/linux/commit/4566bf27069b7780e453cffb24ea5f5323059885):

```
vrrp_nftables.c: In function 'setup_rule_move_igmp':
vrrp_nftables.c:1226:15: error: 'NFT_META_L4PROTO' undeclared (first use in this function)
   add_meta(r, NFT_META_L4PROTO, NFT_REG_1);
               ^
```

Full build log: http://autobuild.buildroot.org/results/213/2132570fb0407abc0e70146d771471e13ef10237/build-end.log

So I would advise to fix this build failure or update the minimum version from 3.10 to 3.14 in [README.kernel_versions](https://github.com/acassen/keepalived/blob/master/README.kernel_versions).

**Comment by pqarmitage** [comment]
@ffontaine Many thanks for reporting this and for the detailed analysis.

Unfortunately we can't update the minimum kernel version to 3.14, because RedHat's RHEL 7 uses kernel 3.10. However RedHat appear to have backported kernel commit [torvalds/linux@4566bf2](https://github.com/torvalds/linux/commit/4566bf27069b7780e453cffb24ea5f5323059885) into their 3.10 kernel [actually nft as a whole has been backported into RHEL kernel 3.10, since nft was first included in Linux 3.13] (having to support current RHEL kernels is an absolute pain since they use such old kernels at the moment). So it appears that this problem only occurs with kernel 3.13.

I have merged commit edc71b1 which instead of effectively using `meta l4proto` now uses `@nh,48,8` if NFT_META_L4PROTO is not declared.

Please update this issue report to confirm whether this resolves your problem: I don't have a system with a 3.13 kernel to test it on.

**Comment by ffontaine** [comment]
edc71b19c619fdc1d71df10a2d0e8f5822965d69 is indeed fixing the issue with kernel < 3.14. Thanks.

However, this is unrelated, but the build then fails on:
```
In file included from ../../lib/rbtree.h:24:0,
                 from ../../lib/rbtree_ka.h:26,
                 from ../../lib/scheduler.h:40,
                 from ../../lib/notify.h:31,
                 from ../../keepalived/include/vrrp.h:41,
                 from ../../keepalived/include/track_process.h:31,
                 from track_process.c:50:
../../lib/rbtree_types.h:31:25: error: initializer element is not constant
 #define RB_ROOT (struct rb_root) { NULL, }
                         ^
```

This error is raised with gcc 4.8 since 48820717cd4a11a184ddc474a29f830c40006bd3.
Do you have a minimal requirement on gcc version?

**Comment by pqarmitage** [comment]
We don't specify a minimum GCC version, but I suppose there will be earliest version of gcc before which it won't compile keepalived.

I have just build keepalived using gcc 4.8.5 (RHEL 7), and that build OK. I can try it with gcc 4.7.2, but it will take a while on that system.

Can you try changing the definition of RB_ROOT to
`#define RB_ROOT (struct rb_root) { NULL, NULL }`
and see if that fixes the problem.

If it does, I will produce a patch that does that if needed.

**Comment by pqarmitage** [comment]
I have just successfully built keepalived with gcc 4.7.2, so it builds with 4.7.2 and 4.8.5. I do seem to remember that odd problems would occur in one gcc version, and then disappear by the next version.

I have just looked more carefully at the definition of struct rb_root, which is:
```
struct rb_root {
        struct rb_node *rb_node;
};
```
and what gcc 4.8.3 is complaining about is
`#define RB_ROOT (struct rb_root) { NULL, }`

I am not sure why there is a comma after NULL, since there is only one element of `struct rb_root`. It might some weird C semantics that I don't understand, but it seems odd having the trailing comma (it is copied from kernel code so it could easily be some clever thing they are doing). I have just removed the trailing comma and recompiled keepalived with gcc 4.7.2 and 11.2.1 and it compiles OK without the comma. Is that worth a try for you?

If you added configure option `--disable-track-process` then it won't attempt to compile track_process.c. Can you add `--disable-track-process` if gcc < 4.9?

**Comment by pqarmitage** [comment]
Oops! I forgot there was also nftables code in the IPVS/checker process. I'll push a patch in a few minutes.

**Comment by pqarmitage** [comment]
Commit 50e8a8d resolves the compile failure in check_nftables.c/

**Comment by ffontaine** [comment]
Everything is building fine with this new commit and `--disable-track-process`, thanks again for your help.
Do you plan a new release soon or should I update buildroot with these 2 patches?

**Comment by pqarmitage** [comment]
It's good to get things like this sorted, and thanks too for your help.

We have not long had a new release, and the nature of the commits since doesn't warrant a new release, so I don't anticipate one in the near future; I think you would be best off updating buildroot with the 2 patches.

Are you happy to close this issue now?

**Comment by ffontaine** [comment]
Sure, I'll update buildroot.
