### ISSUE TITLE
Fail to compile with no args on CentOS 7.6

### ISSUE THREAD

**Issue by huckhuang** [acassen/keepalived#1181]
Environment:
```shell
[root@centos ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@centos ~]# uname -a
Linux centos 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Dependencies Installation:
```shell
[root@centos ~]# yum groupinstall -y 'Development Tools'
[root@centos ~]# yum install -y openssl-devel libnl3-devel ipset-devel iptables-devel file-devel net-snmp-devel glib2-devel json-c-devel pcre2-devel libnftnl-devel libmnl-devel
```

When I configure with no arguments (except `prefix`):
```shell
[root@centos keepalived-2.0.14]# ./configure --prefix=/usr/local/keepalived && make
```

Result about error:
```
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/tmp/keepalived-2.0.14/keepalived/etc'
make[2]: Leaving directory `/tmp/keepalived-2.0.14/keepalived/etc'
make[2]: Entering directory `/tmp/keepalived-2.0.14/keepalived'
  CC       main.o
  CCLD     keepalived
/usr/bin/ld: vrrp/libvrrp.a(vrrp_ip_rule_route_parser.o): undefined reference to symbol '__fpclassify@@GLIBC_2.2.5'
//usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [keepalived] Error 1
make[2]: Leaving directory `/tmp/keepalived-2.0.14/keepalived'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/keepalived-2.0.14/keepalived'
make: *** [all-recursive] Error 1
```

When I configure with `enable-snmp`:
```shell
[root@centos keepalived-2.0.14]# ./configure --prefix=/usr/local/keepalived --enable-snmp && make
```

Compilation is successful:
```
make[1]: Entering directory `/tmp/keepalived-2.0.14/genhash'
  CC       main.o
main.c: In function ‘usage’:
main.c:96:3: warning: string length ‘797’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
   "   --fwmark          -m       Use the specified FW mark.\n");
   ^
  CC       sock.o
  CC       layer4.o
  CC       http.o
  CC       ssl.o
  CCLD     genhash
make[1]: Leaving directory `/tmp/keepalived-2.0.14/genhash'
Making all in bin_install
make[1]: Entering directory `/tmp/keepalived-2.0.14/bin_install'
make[1]: Leaving directory `/tmp/keepalived-2.0.14/bin_install'
make[1]: Entering directory `/tmp/keepalived-2.0.14'
  EDIT     README
make[1]: Leaving directory `/tmp/keepalived-2.0.14'
```

**Comment by pqarmitage** [comment]
Many thanks for reporting this.

Commit 96cf5aa resolves this issue (on Centos, -lm is required when using fpclassify(),  whereas it is not required on Fedora).
