### ISSUE TITLE
Build failure with nftables and kernel < 3.15

### ISSUE THREAD

**Issue by ffontaine** [acassen/keepalived#1678]
**Describe the bug**

Building keepalived 2.12 with nftables on kernel < 3.15 (e.g. with kernel 3.13) raises the following build failure:
```
vrrp_nftables.c:599:33: error: 'NFT_USERDATA_MAXLEN' undeclared (first use in this function)
   udbuf = nftnl_udata_buf_alloc(NFT_USERDATA_MAXLEN);
                                 ^
```

**To Reproduce**
The buildroot logs are available here: http://autobuild.buildroot.org/results/d9bec0a24277202f3271bae35f1188fa8e07d9c0

**Expected behavior**
Build should not fail.

**Keepalived version**
2.1.2

**Distro (please complete the following information):**
 - Buildroot
 - master
 - all architectures

**Additional context**
The build failure is due to commit b10bbfc2a2b216487cea5a586c55765275e41253 which unconditionally uses `NFT_USERDATA_MAXLEN`. However this parameter is only available since kernel 3.15 and https://github.com/torvalds/linux/commit/0768b3b3d228c5acf2075f40f3d25cda30011d4f. Should we disable keepalived with kernel < 3.15 on buildroot or could you check that this parameter is available before using it?

**Comment by pqarmitage** [comment]
Commit b543866 resolves the build failure. Whether Linux 3.15 has sufficient nftables support for keepalived I do not know, and I cannot test it since I do not have system running a 3.13 to 3.15 kernel.
