### ISSUE TITLE
Fails to build with musl libc due to non-standard glib extensions of glob

### ISSUE THREAD

**Issue by jirutka** [acassen/keepalived#1828]
**Describe the bug**

keepalived 2.2.0 fails to build with musl libc due to usage of non-standard GNU libc extensions of glob.

The problematic code was introduced in 73120d9e522f61800e004d7815d8f1137a3682a2.

```
...
parser.c: In function 'open_and_check_glob':
parser.c:1639:9: error: 'glob_t' has no member named 'gl_closedir'
 1639 |  globbuf->gl_closedir = (void *)closedir;
      |         ^~
rbtree.c: In function '__rb_erase_color':
rbtree.c:94:1: warning: inlining failed in call to '__rb_rotate_set_parents': call is unlikely and code size would grow [-Winline]
   94 | __rb_rotate_set_parents(struct rb_node *old, struct rb_node *new,
      | ^~~~~~~~~~~~~~~~~~~~~~~
parser.c:1640:9: error: 'glob_t' has no member named 'gl_readdir'
 1640 |  globbuf->gl_readdir = (void *)readdir;
      |         ^~
rbtree.c:279:5: note: called from here
  279 |     __rb_rotate_set_parents(parent, sibling, root,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  280 |        RB_RED);
      |        ~~~~~~~
rbtree.c:94:1: warning: inlining failed in call to '__rb_rotate_set_parents': call is unlikely and code size would grow [-Winline]
   94 | __rb_rotate_set_parents(struct rb_node *old, struct rb_node *new,
      | ^~~~~~~~~~~~~~~~~~~~~~~
parser.c:1641:9: error: 'glob_t' has no member named 'gl_opendir'
 1641 |  globbuf->gl_opendir = (void *)gl_opendir;
      |         ^~
rbtree.c:371:4: note: called from here
  371 |    __rb_rotate_set_parents(parent, sibling, root,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  372 |       RB_BLACK);
      |       ~~~~~~~~~
rbtree.c:94:1: warning: inlining failed in call to '__rb_rotate_set_parents': call is unlikely and code size would grow [-Winline]
   94 | __rb_rotate_set_parents(struct rb_node *old, struct rb_node *new,
      | ^~~~~~~~~~~~~~~~~~~~~~~
parser.c:1642:9: error: 'glob_t' has no member named 'gl_lstat'
 1642 |  globbuf->gl_lstat = (void *)gl_lstat;
      |         ^~
rbtree.c:383:5: note: called from here
  383 |     __rb_rotate_set_parents(parent, sibling, root,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  384 |        RB_RED);
      |        ~~~~~~~
rbtree.c:94:1: warning: inlining failed in call to '__rb_rotate_set_parents': call is unlikely and code size would grow [-Winline]
   94 | __rb_rotate_set_parents(struct rb_node *old, struct rb_node *new,
      | ^~~~~~~~~~~~~~~~~~~~~~~
parser.c:1643:9: error: 'glob_t' has no member named 'gl_stat'
 1643 |  globbuf->gl_stat = (void *)stat;
      |         ^~
rbtree.c:424:4: note: called from here
  424 |    __rb_rotate_set_parents(parent, sibling, root,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  425 |       RB_BLACK);
      |       ~~~~~~~~~
parser.c:1660:36: error: 'GLOB_ALTDIRFUNC' undeclared (first use in this function)
 1660 |  res = glob(conf_file, GLOB_MARK | GLOB_ALTDIRFUNC
      |                                    ^~~~~~~~~~~~~~~
```

**To Reproduce**

Run on Alpine Linux Edge:

```
# Install build dependencies
apk add build-base openssl-dev popt-dev linux-headers net-snmp-dev libnl3-dev libnfnetlink-dev automake autoconf

./configure \
    --build=$CBUILD \
    --host=$CHOST \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-vrrp \
    --enable-sha1
make
```

**Distro:**
 - Alpine
 - Edge
 - x86_64

**Comment by pqarmitage** [comment]
@jirutka Commit 784a540 resolves this issue. Commits b8eee34 and 61442ca also resolve a couple of compilation warnings that I was seeing on Alpine Linux (3.11.7).

I am not sure why you are getting the rbtree warnings regarding `__rb_rotate_set_parents()`. I don't see those on Alpine Linux 3.11.7 (GCC 9.3.0), nor indeed on any other distro, with GCC up to version 10.2.1. What version of GCC are you using?

**Comment by jirutka** [comment]
> Commit 784a540 resolves this issue. Commits b8eee34 and 61442ca also resolve a couple of compilation warnings…

Thanks, it works now!

> What version of GCC are you using?

gcc 10.2.1_pre1. It’s heavily patched to support some new architectures etc. The source is in https://gitlab.alpinelinux.org/kaniini/alpine-gcc-patches.

I’m getting much more warnings, see the log: [keepalived-build.log](https://github.com/acassen/keepalived/files/5793095/keepalived-build.log)

**Comment by pqarmitage** [comment]
I have looked at  keepalived-build.log and all the warnings are: 
  `warning: inlining failed in call to ...: call is unlikely and code size would grow [-Winline]`

Picking one trivial example, at vrrp_iproute.c line 415, where it warns about inlining `rta_addattr32`. rta_addattr32() is defined as
```
static inline size_t
rta_addattr32(struct rtattr *rta, size_t maxlen, unsigned short type, uint32_t data)
{
        return rta_addattr_l(rta, maxlen, type, &data, sizeof data);
}
```
and `rta_addattr_l()` is not inlined.

So from this, inlining rta_addattr32() saves a function call at the expense of adding one extra parameter. Inlining will therefore clearly reduce the overall code size, and so I think all the warnings you are experiencing are due to a problem with the compiler. When using gcc 10.2.1 on Fedora 33 I don't get the warnings, so I wonder if it is a problem with one of the Alpine gcc patches.

**Comment by jirutka** [comment]
Nope, this is due to building with `-Os`. gcc doesn’t print these warnings when building with `-O2`.

**Comment by pqarmitage** [comment]
OK, thanks for that update. I've now compiled with `-Os` and get the warnings too. As I said above, at least in some cases the warnings do not look sensible so I will have a further look at that.
