### ISSUE TITLE
Beta - doesn't build on CentOS 6.9

### ISSUE THREAD

**Issue by rwgroenenberg** [acassen/keepalived#862]
Building the beta branch (date 2018-05-09) fails on CentOS 6.9 with the following error:

> [rgr@vm1 keepalived.git]$ make
> ...
>   CC     vrrp_snmp.o
> vrrp_snmp.c: In function ‘vrrp_snmp_rule’:
> vrrp_snmp.c:1499: error: ‘ip_rule_t’ has no member named ‘oif’
> vrrp_snmp.c:1501: error: ‘ip_rule_t’ has no member named ‘oif’
> vrrp_snmp.c:1502: error: ‘ip_rule_t’ has no member named ‘oif’
> make[2]: *** [vrrp_snmp.o] Error 1

Configure command used: `./configure --enable-snmp  --with-init=SYSV`

In lib/config.h :
```
/* Define to 1 if you have the declaration of `FRA_OIFNAME', and to 0 if you
   don't. */
#define HAVE_DECL_FRA_OIFNAME 0
```

### Workaround/fix
Adding `#if HAVE_DECL_FRA_OIFNAME .. #endif` around the case-branches in vrrp_snmp.c which use `rule->oif` fixes the build.
[beta_build.txt](https://github.com/acassen/keepalived/files/1987213/beta_build.txt)

further environment info:
```
$ uname -a
Linux vm1 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -q openssl-devel libnl3-devel ipset-devel iptables-devel libnfnetlink-devel
openssl-devel-1.0.1e-57.el6.x86_64
libnl3-devel-3.2.21-8.el6.x86_64
ipset-devel-6.11-4.el6.x86_64
iptables-devel-1.4.7-16.el6.x86_64
libnfnetlink-devel-1.0.0-1.el6.x86_64
$ ./configure --enable-snmp  --with-init=SYSV
...
Keepalived configuration
------------------------
Keepalived version       : 2.0.0
Compiler                 : gcc
Preprocessor flags       :  -I/usr/include/libnl3   
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -Winit-self -g -O2 -D_GNU_SOURCE -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4     -DNETSNMP_ENABLE_IPV6 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_RPM_4_4_COMPAT -Ulinux -Dlinux=linux -I/usr/include/rpm -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib64/perl5/CORE -I/usr/include -DNETSNMP_NO_INLINE
Linker flags             :  -pie
Extra Lib                : -lcrypto -lssl -lnl-genl-3 -lnl-3 -lmagic -L/lib64 -lip4tc -lip6tc -lxtables -L/usr/lib64 -lnetsnmpagent -lnetsnmphelpers -lnetsnmpmibs -lnetsnmp -Wl,-z,relro -Wl,-z,now -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE -ldl
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
Use BFD Framework        : No
SNMP vrrp support        : Yes
SNMP checker support     : Yes
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Json output          : No
libnl version            : 3
Use IPv4 devconf         : No
Use libiptc              : Yes
Use libipset             : Yes
init type                : SYSV
Build genhash            : Yes
Build documentation      : No
```
)

**Comment by pqarmitage** [comment]
Many thanks for this report. I've had a look at your patch there is just one small issue.

route->oif does not depend on HAVE_DECL_FRA_OIFNAME, so could you please try with just the following patch so that the code around VRRP_SNMP_ROUTE_IFINDEX is not removed, to see if it works:
```
@@ -1495,11 +1497,15 @@ vrrp_snmp_rule(struct variable *vp, oid *name, size_t *length,
 			break;
 		*var_len = strlen(rule->iif->ifname);
 		return (u_char *)rule->iif->ifname;
+#if HAVE_DECL_FRA_OIFNAME
 	case VRRP_SNMP_RULE_OUTINTERFACE:
 		if (!rule->oif)
 			break;
 		*var_len = strlen(rule->oif->ifname);
 		return (u_char *)rule->oif->ifname;
+#else
+ 		break;
+#endif
 	case VRRP_SNMP_RULE_TARGET:
 		if (!(rule->action == FR_ACT_GOTO))
 			break;
```

**Comment by rwgroenenberg** [comment]
Ah, yes, good point. My search on oif as a bit too course :/
BTW, the break in the doesn't add much, it just does a break after the return of `case VRRP_SNMP_RULE_ININTERFACE:`

On a site note: just started the beta keepalived, but the only way stop it seems to `killall -9 keepalived`. A kill (w/ or /w/o -9) on the main process doesn't stop everything, nor does a ^C when running with -n. Is it supposed to be that persistent?

**Comment by pqarmitage** [comment]
I've just merged commit 88dbb43 and that has also tidied up the break statements.

You should not do `killall` for keepalived; it is only the parent process that should be signalled. Also, it is the TERM signal that should be sent to terminate keepalived.

`kill -TERM $(cat /var/run/keepalived.pid)` is the best way to stop keepalived (unless you are running keepalived in a network namespace when the location of the pid file moves to a file in /var/run/keepalived/).

**Comment by acassen** [comment]
want me to push a new 1.4.5 ?

**Comment by pqarmitage** [comment]
@acassen - Fortunately this commit only applies to the beta branch. I think we've now managed 8 days since v1.4.4 was released and there have been no issues reported against it (except the SNMP issue which applies across all versions and appears to be an net-snmp issue) and no commits pushed.
